#pragma once

#define VIDEO_WIDTH 384
#define VIDEO_HEIGHT 640

#define DRM_WARPPER_LAYER_UI 1
#define DRM_WARPPER_LAYER_VIDEO 0

#define UI_WIDTH 360
#define UI_HEIGHT 640
#define UI_ROTATION_180
#define UI_Y_OFFSET 120
#define UI_DISPLAY_PIC_PATH "/assets/display.argb"
#define UI_BACKGROUND_COLOR 0xA0000000
#define UI_TEXT_COLOR 0xFFFFFFFF

#define UI_TRANSITION_LOGO_WIDTH 256
#define UI_TRANSITION_LOGO_HEIGHT 256

#define UI_OPERATOR_INFO_WIDTH 360
#define UI_OPERATOR_INFO_HEIGHT 640

#define UI_TRANSITION_ROW_SLEEP 3
#define UI_TRANSITION_LINE_SLEEP 3
#define UI_TRANSITION_OPERATOR_INFO_SLEEP 80
#define UI_TRANSITION_HOLD_TIME 500000ull
#define UI_TRANSITION_LOGO_HOLD_TIME 500000ull
#define UI_TRANSITION_MIDDLE_CB_COUNT 3

#define UI_CONFIG_FILE_PATH "/root/epass_cfg.bin"
#define UI_CONFIG_MAGIC 0x45504153434F4E46
#define UI_CONFIG_VERSION 1

#define UI_BATTERY_ADC_PATH "/sys/bus/iio/devices/iio:device0/in_voltage0_raw"
#define UI_BATTERY_ADC_EMPTY_VALUE 2100
#define UI_BATTERY_ADC_FULL_VALUE 2500
#define UI_BATTERY_ADC_CHARGING_VALUE 2650

#define PRTS_ASSET_PATH "/assets"
#define PRTS_MAX_OPERATORS 50
#define PRTS_OVERLAY_FILENAME "overlay.argb"
#define PRTS_INTRO_VIDEO_FILENAME "intro.mp4"
#define PRTS_INTRO_LOGO_FILENAME "logo.argb"
#define PRTS_LOOP_VIDEO_FILENAME "loop.mp4"
#define PRTS_CONFIG_FILENAME "epconfig.txt"
#define PRTS_FALLBACK_INTRO_LOGO_PATH "/root/rhodes.argb"
#define PRTS_FALLBACK_INTRO_VIDEO_DURATION 8000000ull
#define PRTS_OVERLAY_DISPLAY_OFFSET 3000000ull



#define VBVBUFFERSIZE 1024 * 1024
#define BUF_CNT_4_DI 1
#define BUF_CNT_4_LIST 1
#define BUF_CNT_4_ROTATE 0
#define BUF_CNT_4_SMOOTH 1  